### ISSUE TITLE
Build fails on non-ascii design element names

### ISSUE THREAD

**Issue by lauri-laanti-heeros** [OpenNTF/org.openntf.nsfodp#116]
When design elements have non-ascii characters, ZIP file handling breaks (old and well-known cp437 bug/feature, see e.g. https://bugs.openjdk.java.net/browse/JDK-7062777).

Workaround: rename all design elements

The error stacktrace:
```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: Code/Agents/0. Yll?pito_5c5. Lis?? kentt? (AppCalenda).fa
	at sun.nio.fs.UnixPath.encode(UnixPath.java:162)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:86)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:294)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:65)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.expandZip(ODPCompilerServlet.java:217)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```

**Comment by jesse-gallagher** [comment]
Good idea - I’ll take a crack at the workaround when I have a chance.

**Comment by lauri-laanti-heeros** [comment]
Sorry, I was unclear. The workaround (manual renaming of files inside ODP) allows build to proceed but the resulting elements have incorrect names.
Fix could be to use UTF-8 both while creating and extracting the ZIP file.
