### ISSUE TITLE
NullPointerException with some image resources

### ISSUE THREAD

**Issue by lauri-laanti-heeros** [OpenNTF/org.openntf.nsfodp#129]
This is repeatable with attached NSF (contains only 1 image resource)
[imgres.zip](https://github.com/OpenNTF/org.openntf.nsfodp/files/3717817/imgres.zip)
 

```
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.heeros:imageresource-test >--------------------
[INFO] Building imageresource-test 0.0.1
[INFO] -----------------------------[ domino-nsf ]-----------------------------
[INFO]
[INFO] --- nsfodp-maven-plugin:2.5.0-SNAPSHOT:generate-pde-structure (default-generate-pde-structure) @ imageresource-test ---
[INFO]
[INFO] --- nsfodp-maven-plugin:2.5.0-SNAPSHOT:create-source-folders (default-create-source-folders) @ imageresource-test ---
[INFO]
[INFO] --- nsfodp-maven-plugin:2.5.0-SNAPSHOT:generate-metadata (default-generate-metadata) @ imageresource-test ---
[INFO]
[INFO] --- nsfodp-maven-plugin:2.5.0-SNAPSHOT:compile (default-compile) @ imageresource-test ---
[INFO] Compiling ODP
[INFO] Compiling with server: https://<XXX>/org.openntf.nsfodp/compiler
[INFO] Installing bundles
[INFO] - Installed no bundles
[INFO] Creating destination NSF
[INFO] Importing DB properties
[INFO] Importing basic design elements
[INFO] Importing file resources
[INFO] Uninstalling bundles
java.lang.NullPointerException
	at com.ibm.commons.xml.DOMUtil.createElement(DOMUtil.java:1007)
	at org.openntf.nsfodp.commons.dxl.DXLUtil.writeItemDataRaw(DXLUtil.java:142)
	at org.openntf.nsfodp.commons.odp.ImageResource.attachFileData(ImageResource.java:59)
	at org.openntf.nsfodp.commons.odp.AbstractSplitDesignElement.getDxl(AbstractSplitDesignElement.java:71)
	at org.openntf.nsfodp.commons.odp.FileResource.getDxl(FileResource.java:75)
	at org.openntf.nsfodp.compiler.ODPCompiler.lambda$22(ODPCompiler.java:789)
	at org.openntf.nsfodp.compiler.ODPCompiler$$Lambda$65.00000000CC628D40.apply(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1332)
	at java.util.stream.Collectors$$Lambda$48.00000000CC5FBE50.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:180)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:186)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1391)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:719)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:510)
	at org.openntf.nsfodp.compiler.ODPCompiler.importFileResources(ODPCompiler.java:785)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:438)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:346)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.lambda$2(ODPCompilerServlet.java:191)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet$$Lambda$33.00000000CC488DE0.run(Unknown Source)
	at lotus.domino.NotesThread.run(Unknown Source)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:199)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at [com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)]
```

**Comment by jesse-gallagher** [comment]
I can see the same thing with that image resource, so this is definitely confirmable as a bug.

**Comment by jesse-gallagher** [comment]
Ahh, I see what's going on. This is actually less an independent bug and more dependent on https://github.com/OpenNTF/org.openntf.nsfodp/issues/20 . Because the ODP isn't using "use binary DXL", the metadata file has an `imageresource` root element instead of the expected `note`. I'd like to support these, but it'll be a larger project.

In the mean time, I at least improved the error messages for this case.
