### ISSUE TITLE
Example activator may cause NPE

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#174]
This showed up during compilation on Windows, and it's possible that this is a side effect of some other trouble. That's particularly likely given that the NPE is when trying to get a log:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:349)
	at org.eclipse.core.runtime.Platform.getLog(Platform.java:976)
	at org.openntf.nsfodp.example.Activator.<init>(Activator.java:37)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1843)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:758)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:711)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:310)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	... 22 more
```

https://github.com/prominic/Moonshine-IDE/issues/646#issuecomment-578174834

**Comment by feather812002** [comment]
```
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Users\ADMINI~1\AppData\Local\Temp\lib-jsf-api.jar883234003555450250.jar: This file is in use by another program and cannot be accessed by the process.
	at org.openntf.nsfodp.compiler.equinox.CompilerApplication.lambda$4(CompilerApplication.java:96)
	at org.openntf.nsfodp.compiler.equinox.CompilerApplication$$Lambda$37.04D86D18.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at lotus.domino.NotesThread.run(Unknown Source)
Caused by: java.nio.file.FileSystemException: C:\Users\ADMINI~1\AppData\Local\Temp\lib-jsf-api.jar883234003555450250.jar: This file is in use by another program and cannot be accessed by the process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:98)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:109)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:114)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:281)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:120)
	at java.nio.file.Files.deleteIfExists(Files.java:1176)
	at com.ibm.xsp.extlib.javacompiler.impl.SourceFileManager.close(SourceFileManager.java:369)
	at com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.close(JavaSourceClassLoader.java:232)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:511)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:346)
	at org.openntf.nsfodp.compiler.equinox.CompilerApplication.lambda$4(CompilerApplication.java:90)
	... 6 more

```

I see this line from terminal of windows :

lib-jsf-api.jar883234003555450250.jar: This file is in use by another program and cannot be accessed 

it look like still belong to Xpage lib , and I don't know why it always be use other program .
