### ISSUE TITLE
Maven local compilation reports a non-zero Equinox exit code even after success on Windows

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#187]
This continues without issue on macOS.

```
[INFO] Compiling ODP
Installing bundles
- Installed  1 bundle
Initializing libraries
Compiling Java source
- Compiling  1 class
Compiling custom controls
Compiling XPages
Creating destination NSF
Importing DB properties
Importing basic design elements
Importing file resources
Importing LotusScript libraries
- Compiling LotusScript
Importing custom controls
Importing XPages
Importing Java design elements
Uninstalling bundles
org.openntf.nsfodp.compiler.equinox.CompilerApplication#end
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for NSF ODP Tooling Example Project 1.0.0:
[INFO]
[INFO] NSF ODP Tooling Example Project .................... SUCCESS [  0.317 s]
[INFO] org.openntf.nsfodp.example ......................... SUCCESS [  2.378 s]
[INFO] org.openntf.nsfodp.example.feature ................. SUCCESS [  0.598 s]
[INFO] org.openntf.nsfodp.example.updatesite .............. SUCCESS [  6.248 s]
[INFO] nsf-example ........................................ FAILURE [ 10.849 s]
[INFO] NSF ODP Tooling Example Distribution ZIP ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.937 s
[INFO] Finished at: 2020-04-08T16:22:54-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openntf.maven:nsfodp-maven-plugin:3.0.0-SNAPS
HOT:compile (default-compile) on project nsf-example: Exception while compiling
the NSF: Encountered exception while launching application: Equinox process exit
ed with status code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <args> -rf :nsf-example
```

**Comment by jesse-gallagher** [comment]
This is likely related to a post-service exception seen on a Windows server, to do with file deletion:

```
java.nio.file.FileSystemException: C:\Users\Jesse\AppData\Local\Temp\notes74483D\odpcompilertemp4742045750823717348.nsf: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.openntf.nsfodp.commons.NSFODPUtil.deltree(NSFODPUtil.java:58)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServle
		t.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.jav
		a:181)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```
