### ISSUE TITLE
Deployment in 3.0.0-M2 fails with ClassNotFoundException

### ISSUE THREAD

**Issue by eivindr** [OpenNTF/org.openntf.nsfodp#190]
When testing the deployment feature in 3.0.0-M2, I'm getting an error:

> 4/19/20 7:23 PM: Exception Thrown
javax.servlet.ServletException: org.eclipse.core.runtime.CoreException: Plug-in org.openntf.nsfodp.deployment was unable to load class org.openntf.nsfodp.deployment.servlet.NSFDeploymentServlet.
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.initializeDelegate(ServletManager.java:198)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:179)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.openntf.nsfodp.deployment was unable to load class org.openntf.nsfodp.deployment.servlet.NSFDeploymentServlet.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.initializeDelegate(ServletManager.java:194)
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.openntf.nsfodp.deployment.servlet.NSFDeploymentServlet cannot be found by org.openntf.nsfodp.deployment_3.0.0.202004082145
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:853)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:565)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 18 more

When inspecting org.openntf.nsfodp.deployment.servlet_3.0.0.202004082145.jar I notice the .class files are missing (compared to the 2.1.0 release).

**Comment by eivindr** [comment]
Sorry, I inspected the wrong file when comparing. The jars in both releases looks the same. So, not sure about the error..

**Comment by jesse-gallagher** [comment]
I'll check on this, but the whole deployment capability - local and on server - is still pretty half-baked and not really good for real use yet.

**Comment by eivindr** [comment]
It looks like it might be a build issue since there are no .class files in the deployment servlet jar?

I have no problem alpha/beta test the feature ;)
