### ISSUE TITLE
Fix local compilation on Linux

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#213]
Getting the Notes runtime working on Linux is tricky. It's close now, but fails on setting a DXL exporter property with the NAPI or on DXL import with lsxbe (presumably at the same internal place).

Properly passing the executable directory and INI file in `NotesInitExtended` helped, but it still ends up emitting an exception with no associated message. It may be that the launcher needs to also include `${notes-program}/res/C` in the `PATH` environment variable, as I have done in tests on Linux. Also maybe `Directory`, though the INI part may cover that.

**Comment by jesse-gallagher** [comment]
Adding `res/C` to the path helped in the sense that now there's a proper exception message:

```
Caused by: com.darwino.domino.napi.DominoException: Invalid Property Value for Property specified
	at com.darwino.domino.napi.DominoAPIImpl.DXLSetImporterProperty(Native Method)
	at com.darwino.domino.napi.wrap.NSFDXLImporter.setDesignImportOption(NSFDXLImporter.java:58)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:444)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:357)
	at org.openntf.nsfodp.compiler.equinox.CompilerApplication.lambda$4(CompilerApplication.java:104)
	... 6 more
```

I'm not sure why this is, as the same build of the compiler works locally on macOS.

**Comment by jesse-gallagher** [comment]
It's possible that this is a problem at the NAPI level, perhaps with an incorrect native-enum size (which is only vaguely defined) or with needing `calloc` instead of `malloc`. That wouldn't really explain why it previously failed with the lsxbe importer, but it could be that that would have been fixed by just the `res/C` addition.

**Comment by jesse-gallagher** [comment]
That looks to have been it: switching from `malloc` to `calloc` made it compile reliably so far.
