### ISSUE TITLE
Compiler breaks when the NSF subclasses both XSP core artifacts and custom-bundle artifacts that also do so

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#231]
```
Caused by: java.lang.LinkageError: loading constraint violation when overriding method "some/plugin/renderer/UIViewRootRenderer.addCommonResources(Ljavax/faces/context/FacesContext;Lcom/ibm/xsp/component/UIViewRootEx;Ljava/util/List;)V" during creation of class "some/nsf/renderer/UIViewRootRenderer": loader "com/ibm/xsp/extlib/javacompiler/JavaSourceClassLoader@46589c6a" of class "some/nsf/renderer/UIViewRootRenderer" and loader "java/net/URLClassLoader@8d8f8405" of class "some/plugin/renderer/UIViewRootRenderer" have different types for the method signature
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:314)
	at com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.findClass(JavaSourceClassLoader.java:159)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.addClasses(JavaSourceClassLoader.java:244)
	... 24 more
```

**Comment by jesse-gallagher** [comment]
Bizarrely, in an example project, this breaks when both such a subclass and a `javax.faces.el.VariableResolver` subclass are present in the NSF. It could be related to the "container" classloaders I set up before for XSP files - if the same thing is being used here, it could lead to odd class chains when multiple compilation cycles load the same base classes.

**Comment by jesse-gallagher** [comment]
Having two classes in the NSF that both inherit from core XSP classes works fine - my guess is that it's a combination of having XSP classes loaded by way of a different bundle plus using core ones. I'm not sure _why_ that would be the case, since both custom bundle classes and core XSP classes are loaded the same way, but it makes a sort of sense to go on.

**Comment by jesse-gallagher** [comment]
I'm not sure how they're going awry here - classloading isn't done via OSGi, but is instead built from filesystem references to OSGi bundles on disk. I thought that it might be due to the base classloader in use, but switching that to the root system classloader (even above the AppClassLoader) did not change the behavior.

Importantly, this exception happens when loading the classes back out of the compilation environment, not when compiling them in the first place.
