### ISSUE TITLE
Observed import trouble when an SVG is present in Resources/Files

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#232]
The SVG file had an associated metadata file.

```
java.lang.IllegalStateException: Root element <note> not found. This is most likely because the ODP is not using binary DXL, and this is currently unsupported
	at org.openntf.nsfodp.commons.dxl.DXLUtil.getRootNoteElement(DXLUtil.java:377)
	at org.openntf.nsfodp.commons.dxl.DXLUtil.deleteItems(DXLUtil.java:73)
	at org.openntf.nsfodp.commons.dxl.DXLUtil.writeItemDataRaw(DXLUtil.java:134)
	at org.openntf.nsfodp.commons.odp.AbstractSplitDesignElement.attachFileData(AbstractSplitDesignElement.java:86)
	at org.openntf.nsfodp.commons.odp.AbstractSplitDesignElement.getDxl(AbstractSplitDesignElement.java:71)
	at org.openntf.nsfodp.commons.odp.FileResource.getDxl(FileResource.java:75)
	at org.openntf.nsfodp.compiler.ODPCompiler.lambda$9(ODPCompiler.java:624)
	at org.openntf.nsfodp.compiler.ODPCompiler$$Lambda$133/000000002193E550.apply(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.Collectors$$Lambda$87/00000000204B4B90.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openntf.nsfodp.compiler.ODPCompiler.importFileResources(ODPCompiler.java:620)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:368)
	at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:305)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.lambda$2(ODPCompilerServlet.java:196)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet$$Lambda$40/000000002081D510.run(Unknown Source)
	at lotus.domino.NotesThread.run(Unknown Source)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:204)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```

**Comment by shillem** [comment]
I have further information regarding this problem.
The odp .metadata representation of the file, when created and managed through DDE and its source control, is the following for me:

```
<?xml version="1.0" encoding="UTF-8"?>
<fileresource xmlns="http://www.lotus.com/dxl" mimetype="image/svg+xml" name="vendors/coreui/icons/sprites/free.svg" publicaccess="true"/>
```

That's basically what DDE outputs for the associated metadata file. Same thing happens if I use `mvn org.openntf.maven:nsfodp-maven-plugin:export-odp` but the latter adds a nested and meaty `filedata` tag to it:

```
<?xml version="1.0" encoding="UTF-8"?>
<fileresource mimetype="image/svg+xml"
  name="vendors_2fcoreui_2ficons_2fsprites_2ffree.svg"
  publicaccess="true" xmlns="http://www.lotus.com/dxl">
  <filedata>
PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgc3R5bGU9InBvc2l0aW9uOiBhYnNvbHV0ZTsgd2lkdGg6
IDA7IGhlaWdodDogMDsgb3ZlcmZsb3c6IGhpZGRlbjsiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0
...
```

So, the error is because the compiler expects the `note` tag rather than the `fileresource` one.

Now, if I worf from eclipse and add just the svg while ignoring the original metadata file, when mvn compiles the .medata file generated has the following structure (I went in there and modified the `$MimeType` text value to put what I wanted although I'm not sure where to put the public access flag. I have to look it up):

```
<?xml version="1.0" encoding="UTF-8"?>
<note class="form" xmlns="http://www.lotus.com/dxl">
  <item name="$TITLE">
    <text>vendors_2fcoreui_2ficons_2fsprites_2ffree.svg</text>
  </item>
  <item name="$Flags">
    <text>345CgQ</text>
  </item>
  <item name="$FlagsExt">
    <text>D</text>
  </item>
  <item name="$FileNames">
    <text>vendors_2fcoreui_2ficons_2fsprites_2ffree.svg</text>
  </item>
  <item name="$MimeType">
    <text>image/svg+xml</text>
  </item>
  <item name="$FileModDT">
    <datetime>20200429T105553,00+02</datetime>
  </item>
</note>
```

Anyway, it seems that despite the different structure the output nsf contains the svg and the correct mime type (minus the public access that I didn't know how to set on the fly).

**Comment by jesse-gallagher** [comment]
Ahhhhh, that makes sense. There’s another issue in here somewhere for me to complete support for non-“note” metadata files, and this is as good a place as any to start.
