### ISSUE TITLE
Observed exception in server-based execution with non-ASCII file names

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#257]
I observed this using the "xpages-library" example, which includes an agent named "Example Agent with refäräns.fa". When compiling via a server (11.0.1FP2 in Docker), this resulted in:

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: Code/Agents/Example Agent with ref?r?ns.fa
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.expandZip(ODPCompilerServlet.java:241)
	at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:153)
```

I figure either the client zipping process doesn't encode with UTF-8 or the server unzip doesn't properly decode with it.

**Comment by jesse-gallagher** [comment]
Oddly, both sides are already interpreting the file using UTF-8.

**Comment by jesse-gallagher** [comment]
We could avoid this using Apache Commons: https://stackoverflow.com/questions/15519493/how-to-add-zip-entry-with-utf-8-name-to-zip . However, it'd probably be quicker to just mask/filter non-ASCII characters in file names, since they don't actually matter when compiling.

**Comment by jesse-gallagher** [comment]
The trouble isn't with zipped files as such - exporting an agent with that name causes the same trouble on that system. That's likely to do with https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable .

Oddly, the LANG in the Docker container is already "C.utf8". I'll have to test setting it to something else, such as "C.UTF-8" or "en_us.UTF-8", to see if it makes a difference. This question talks about the use of that variable: https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable

**Comment by jesse-gallagher** [comment]
This seems to be a general problem in this Linux environment, even when not extracting the files out to the filesystem: when working out of the ZIP directly, the agent is imported but with its name mangled, which makes me wonder if Domino is also picking up a bad encoding internally. Oddly, setting LANG="en_us.UTF-8" in the Dockerfile didn't fix it.
