### ISSUE TITLE
Encountered "special database object cannot be located" on server but not client

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#261]
This occurred in the 3.5.0-SNAPSHOT stream, exporting a database located on a second, distinct server referenced like -DdatabasePath=server!!foo.nsf.

```
02/16/2021 15:25:59   HTTP JVM: org.openntf.nsfodp.commons.odp.notesapi.NDominoException: com.darwino.domino.napi.DominoException: Special database object cannot be located
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.notesapi.darwinonapi.DarwinoNDatabase.getNoteByID(DarwinoNDatabase.java:43)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.ODPExporter.export(ODPExporter.java:298)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.servlet.ODPExporterServlet.handle(ODPExporterServlet.java:148)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.servlet.ODPExporterServlet.doGet(ODPExporterServlet.java:61)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:693)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
02/16/2021 15:25:59   HTTP JVM: Caused by: 
02/16/2021 15:25:59   HTTP JVM: com.darwino.domino.napi.DominoException: Special database object cannot be located
02/16/2021 15:25:59   HTTP JVM: 	at com.darwino.domino.napi.DominoAPIImpl.NSFNoteOpenExt(Native Method)
02/16/2021 15:25:59   HTTP JVM: 	at com.darwino.domino.napi.wrap.NSFDatabase.getNoteByID(NSFDatabase.java:124)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.notesapi.darwinonapi.DarwinoNDatabase.getNoteByID(DarwinoNDatabase.java:40)
02/16/2021 15:25:59   HTTP JVM: 	... 19 more
02/16/2021 15:25:59   HTTP JVM: Encountered native exception while processing special note 256: com.darwino.domino.napi.DominoException: Special database object cannot be located
02/16/2021 15:25:59   HTTP JVM: org.openntf.nsfodp.commons.odp.notesapi.NDominoException: com.darwino.domino.napi.DominoException: Special database object cannot be located
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.notesapi.darwinonapi.DarwinoNDatabase.getNoteByID(DarwinoNDatabase.java:43)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.ODPExporter.export(ODPExporter.java:298)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.servlet.ODPExporterServlet.handle(ODPExporterServlet.java:148)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.exporter.servlet.ODPExporterServlet.doGet(ODPExporterServlet.java:61)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:693)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
02/16/2021 15:25:59   HTTP JVM: 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
02/16/2021 15:25:59   HTTP JVM: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
02/16/2021 15:25:59   HTTP JVM: 	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
02/16/2021 15:25:59   HTTP JVM: Caused by: 
02/16/2021 15:25:59   HTTP JVM: com.darwino.domino.napi.DominoException: Special database object cannot be located
02/16/2021 15:25:59   HTTP JVM: 	at com.darwino.domino.napi.DominoAPIImpl.NSFNoteOpenExt(Native Method)
02/16/2021 15:25:59   HTTP JVM: 	at com.darwino.domino.napi.wrap.NSFDatabase.getNoteByID(NSFDatabase.java:124)
02/16/2021 15:25:59   HTTP JVM: 	at org.openntf.nsfodp.notesapi.darwinonapi.DarwinoNDatabase.getNoteByID(DarwinoNDatabase.java:40)
02/16/2021 15:25:59   HTTP JVM: 	... 19 more
02/16/2021 15:25:59   HTTP JVM: Encountered native exception while processing special note 2: com.darwino.domino.napi.DominoException: Special database object cannot be located
```

**Comment by jesse-gallagher** [comment]
This also led to "Unexpected end of ZLIB input stream" on the client, masking the problem on the server.
