### ISSUE TITLE
Investigate AccessDeniedExceptions in many operations on Windows

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#269]
This may currently hit access-denied exceptions even when not actively working with the odp folder in another app.

**Comment by jesse-gallagher** [comment]
This can happen when generating/exporting an ODP when the destination exists, and can also happen when working with the scratch space, even though `createDirectories` should be safe:

```
Caused by: java.nio.file.AccessDeniedException: c:\Git\icrc\buildtest\target\nsf
odpequinox\plugins
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsE
xception.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(Window
sFileSystemProvider.java:509)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:79
7)
        at java.base/java.nio.file.Files.createDirectories(Files.java:783)
        at org.openntf.nsfodp.commons.osgi.EquinoxRunner.start(EquinoxRunner.jav
a:111)
        at org.openntf.maven.nsfodp.equinox.AbstractEquinoxTask.run(AbstractEqui
noxTask.java:195)
        ... 25 more
```

**Comment by jesse-gallagher** [comment]
This may be trouble with "delete pending" on Windows:

https://bugs.openjdk.java.net/browse/JDK-8029608
https://bugs.openjdk.java.net/browse/JDK-8024496

**Comment by jesse-gallagher** [comment]
For the parts relating to the target/nsfodpequinox directory, it might work to put a random number in the directory name. It wouldn't fix trouble if `target` itself is part of the problem, but it'd lower the churn with the subdirectories.

**Comment by mpradny** [comment]
The problem seems to be caused by the sequence of setWorkingDirectory and start calls, where the first one creates the directories and the second tries to delete them and recreate them.

**Comment by mpradny** [comment]
![image](https://user-images.githubusercontent.com/12035342/118666006-1b6d0e80-b7f3-11eb-8942-bdbcb79f650d.png)
See https://stackoverflow.com/questions/48311252/a-bit-strange-behaviour-of-files-delete-and-files-deleteifexists
