### ISSUE TITLE
Observed FacesPageException when a CC uses an ExecuteScriptAction property

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#274]
The CC's xsp-config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<faces-config>
  <faces-config-extension>
    <namespace-uri>http://www.ibm.com/xsp/custom</namespace-uri>
    <default-prefix>xc</default-prefix>
  </faces-config-extension>
  <composite-component>
    <component-type>cc_simple</component-type>
    <composite-name>cc_simple</composite-name>
    <composite-file>/cc_simple.xsp</composite-file>
    <composite-extension>
      <designer-extension>
        <in-palette>true</in-palette>
      </designer-extension>
    </composite-extension>
    <property>
      <property-name>eventHandlerServer</property-name>
      <property-class>com.ibm.xsp.actions.ExecuteScriptAction</property-class>
      <display-name/>
    </property>
  </composite-component>
</faces-config>
```

The calling XSP:

```xml
	<xc:cc_simple>
		<xc:this.eventHandlerServer>
			<xp:executeScript script="#{javascript:print('test')}"></xp:executeScript>
		</xc:this.eventHandlerServer>
	</xc:cc_simple>
```

The final exception:

```
Caused by: com.ibm.xsp.page.FacesPageException: The value of the property eventHandlerServer cannot be the tag xp:executeScript, because it is not an instance of com.ibm.xsp.actions.ExecuteScriptAction.
	at com.ibm.xsp.page.parse.DefaultDeserialHandler.handlePropertyBadTypeTag(DefaultDeserialHandler.java:374)
	at com.ibm.xsp.page.parse.PropertyValueValidator.valueIsFacesInstance(PropertyValueValidator.java:188)
	at com.ibm.xsp.page.parse.PropertyValueValidator.checkAllowed(PropertyValueValidator.java:176)
	at com.ibm.xsp.page.parse.PropertyValueValidator.setValue(PropertyValueValidator.java:237)
	at com.ibm.xsp.page.parse.PropertyHandler.setValue(PropertyHandler.java:73)
	at com.ibm.xsp.page.parse.FacesDeserializer.readComplexInstance(FacesDeserializer.java:588)
	at com.ibm.xsp.page.parse.FacesDeserializer.readPropertyTagContents(FacesDeserializer.java:1026)
	at com.ibm.xsp.page.parse.FacesDeserializer.readPropertyTag(FacesDeserializer.java:867)
	at com.ibm.xsp.page.parse.FacesDeserializer.readComponentContents(FacesDeserializer.java:258)
	at com.ibm.xsp.page.parse.FacesDeserializer.readComponentInstance(FacesDeserializer.java:782)
	at com.ibm.xsp.page.parse.FacesDeserializer.readComponentContents(FacesDeserializer.java:264)
	at com.ibm.xsp.page.parse.FacesDeserializer.readComponentInstance(FacesDeserializer.java:782)
	at com.ibm.xsp.page.parse.FacesDeserializer.readMarkupTagContents(FacesDeserializer.java:1116)
	at com.ibm.xsp.page.parse.FacesDeserializer.readRoot(FacesDeserializer.java:169)
	at com.ibm.xsp.extlib.interpreter.DynamicXPageBean.translate(DynamicXPageBean.java:256)
	at org.openntf.nsfodp.compiler.ODPCompiler.compileXSP(ODPCompiler.java:809)
	... 9 more
```

**Comment by jesse-gallagher** [comment]
It seems like the registry in use here isn't picking up that `xp:executeScript` is indeed `ExecuteScriptAction`. This is odd to me, since it seems like that would imply tremendous trouble elsewhere, yet this is the first I've seen of it.

**Comment by jesse-gallagher** [comment]
The exception is the same both when running locally and when running against an existing Domino server.

**Comment by jesse-gallagher** [comment]
The class name reported in the tag as it's going matches, so I'm not sure what the core trouble is. It's possible that it's a class-loading issue, either that the two class objects used in the `paramClass.isAssignableFrom(this._definition.getJavaClass())` test are from different loaders or that the latter is null. I don't know why it wouldn't be able to find the class, though, since it's a core XPages class.

**Comment by jesse-gallagher** [comment]
In debugging it, it does indeed seem to be most likely a class-loader problem - though both the `PropertyValueValidator` and the incoming `FacesItemInstance` declare that they're `com.ibm.xsp.actions.ExecuteScriptAction`, they're different instance and come from distinct immediate classloaders. The former's `_itemClass` property comes from a `URLClassLoader` (probably one I build), while the latter comes from an `EquinoxClassLoader` (presumably the runtime's actual class loader).
