### ISSUE TITLE
Windows holds on to a number of temporary files

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#276]
The deletion exceptions are intentionally squelched by NSFODPUtil.deltree and they're just temp files, but it would be best to remove them all if possible.

After a build of the xpages-library example:

![Screen Shot 2021-05-19 at 8 03 51 AM](https://user-images.githubusercontent.com/935700/118809544-c378eb00-b878-11eb-9943-f22632368955.png)

**Comment by jesse-gallagher** [comment]
Fixed in the Bazaar

**Comment by jesse-gallagher** [comment]
This was mostly fixed, but can still show up in practice:

![image](https://user-images.githubusercontent.com/935700/119388647-91142700-bc98-11eb-94a3-12a572219d2f.png)

**Comment by jesse-gallagher** [comment]
This still remains for classpath JARs extracted by ODPCompilerServlet:

```
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM: java.nio.file.FileSystemException: C:\Users\Jesse\AppData\Local\Temp\notes74483D\classpathJar5737077315197458
021.jar: The process cannot access the file because it is being used by another process.
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at java.nio.file.Files.deleteIfExists(Files.java:1165)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.openntf.nsfodp.commons.NSFODPUtil.deltree(NSFODPUtil.java:92)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.openntf.nsfodp.commons.NSFODPUtil.deltree(NSFODPUtil.java:72)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:242)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:
180)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:
90)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.j
ava:181)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
[0C50:000B-0AD0] 07/06/2021 09:00:07 AM  HTTP JVM:      at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```
