### ISSUE TITLE
Windows Equinox container fails to launch due to unresolved lotus.domino package

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#294]
This seems to have shown up recently, and currently fails in 3.8.1-SNAPSHOT.

```
!SESSION 2022-02-03 18:25:02.446 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=1.8.0_282-b08
JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20210120_972 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -framwork c:\Git\icrc\cihl\target\nsfodpequinox
Command-line arguments:  -framwork c:\Git\icrc\cihl\target\nsfodpequinox -consoleLog

!ENTRY org.openntf.nsfodp.compiler 4 0 2022-02-03 18:25:04.553
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.openntf.nsfodp.compiler [6]
  Unresolved requirement: Import-Package: lotus.domino

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.openntf.nsfodp.transpiler 4 0 2022-02-03 18:25:04.559
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.openntf.nsfodp.transpiler [11]
  Unresolved requirement: Import-Package: lotus.domino

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by jesse-gallagher** [comment]
This appears to have worked in 3.6.0 but is broken afterwards.

**Comment by jesse-gallagher** [comment]
This is quite likely a problem with the upstream generate-domino-update-site project: the generated update site in use exports the Notes.jar packages like `lotus\domino`, which naturally won't work.
