### ISSUE TITLE
java.lang.IllegalStateException: Recursive update

### ISSUE THREAD

**Issue by edy** [OpenNTF/org.openntf.nsfodp#327]
Hi Jesse,

We are in the process of migrating from Domino 12 to 14 and ran into an error when compiling the sources with the nsfodp maven plugin using the latest Domino docker image (14.0FP2).

Looking at the code, I came across this comment:

> Using computeIfAbsent here with concurrentcy-safe types causes exceptions on Java > 8

https://github.com/OpenNTF/org.openntf.nsfodp/blob/57900325cfde6d26b8e0f7670b967f1e1b5f91bf/nsfodp/bundles/org.openntf.nsfodp.compiler/src/org/openntf/com/ibm/xsp/extlib/javacompiler/JavaSourceClassLoader.java#L151C4-L151C92

And since Domino 14 uses Java 17, maybe this is the cause of the error?

```
> mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\Users\edy\apache-maven-3.9.9
Java version: 21.0.4, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-21.0.4.7-hotspot
Default locale: de_DE, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

```
> mvn package

[INFO]
[INFO] --- nsfodp:4.0.5:compile (default-compile) @ Edy ---
[INFO] Compiling ODP
[INFO] Writing ACL from pom.xml into AppProperties/database.properties
[INFO] Compiling with server: http://mydominoserver:8052/org.openntf.nsfodp/compiler
[INFO] Installing bundles
[INFO] - Installed no bundles
[INFO] Initializing libraries
[INFO] Compiling Java source
[INFO] - Compiling 1,288 classes
[INFO] Uninstalling bundles
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Java compilation failed:

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.doPost(ODPCompilerServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.handleRequest(ServletRegistration.java:90)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:111)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:59)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
        at com.ibm.domino.xsp.adapter.osgi.OSGIModule.invokeServlet(OSGIModule.java:167)
        at com.ibm.domino.xsp.adapter.osgi.OSGIModule.access$0(OSGIModule.java:153)
        at com.ibm.domino.xsp.adapter.osgi.OSGIModule$1.invokeServlet(OSGIModule.java:134)
        at com.ibm.domino.xsp.adapter.osgi.AbstractOSGIModule.invokeServletWithNotesContext(AbstractOSGIModule.java:181)
        at com.ibm.domino.xsp.adapter.osgi.OSGIModule.doService(OSGIModule.java:128)
        at com.ibm.domino.xsp.adapter.osgi.OSGIService.doService(OSGIService.java:418)
        at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
        at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
        at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
Caused by: java.lang.RuntimeException: Java compilation failed:

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

        at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:451)
        at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:336)
        at org.openntf.nsfodp.compiler.servlet.ODPCompilerServlet.lambda$3(ODPCompilerServlet.java:217)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at lotus.domino.NotesThread.run(Unknown Source)
Caused by: org.openntf.com.ibm.xsp.extlib.javacompiler.JavaCompilerException: Error while loading the compiled classes
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.addClasses(JavaSourceClassLoader.java:253)
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.addClasses(JavaSourceClassLoader.java:208)
        at org.openntf.nsfodp.compiler.ODPCompiler.compileJavaSources(ODPCompiler.java:491)
        at org.openntf.nsfodp.compiler.ODPCompiler.compile(ODPCompiler.java:390)
        ... 6 more
Caused by: java.lang.IllegalStateException: Recursive update
        at java.base/java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap.java:2560)
        at java.base/java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2362)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1784)
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.findClass(JavaSourceClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1197)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1112)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)
        at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:385)
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.lambda$2(JavaSourceClassLoader.java:162)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.findClass(JavaSourceClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1197)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1112)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1095)
        at org.openntf.com.ibm.xsp.extlib.javacompiler.JavaSourceClassLoader.addClasses(JavaSourceClassLoader.java:248)
        ... 9 more
```

**Comment by jesse-gallagher** [comment]
Seems very likely indeed - I'll take a look.

**Comment by jesse-gallagher** [comment]
I pushed up version 4.0.6, which should hopefully fix this - I replaced that computeWithForm call with a utility method that does similarly to what the surrounding block did.
