### ISSUE TITLE
Invalid characters cause the FacesReader to throw up its hands

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#4]
```Caused by: org.xml.sax.SAXParseException: Invalid byte 3 of 3-byte UTF-8 sequence.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at com.ibm.xsp.util.DomUtil.parse(DomUtil.java:84)
	at com.ibm.xsp.page.parse.FacesReader.<init>(FacesReader.java:74)
	at com.ibm.xsp.extlib.interpreter.DynamicXPageBean.translate(DynamicXPageBean.java:230)
	at org.openntf.xsp.extlibx.bazaar.odpcompiler.ODPCompiler.compileXSP(ODPCompiler.java:702)```

**Comment by jesse-gallagher** [comment]
This happens with valid Czech characters as well, so it's not just a matter of invalid incoming data. 

[foo.txt](https://github.com/OpenNTF/org.openntf.nsfodp/files/6502557/foo.txt)
