### ISSUE TITLE
Investigate using the framework/osgi folders from notes-program in Equinox apps

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.nsfodp#89]
Currently, the Equinox mojos require both notes-program and notes-platform, but it's probably fair to assume that the notes-program directory will also contain the platform files. I'm not sure if there are oddities with unpacked plugins, but presumably there's SOME way to use them, since Notes does.

**Comment by jesse-gallagher** [comment]
In my initial attempts, this kept running into:

```
[ERROR] !SESSION Tue Jan 07 09:51:55 EST 2020 ------------------------------------------
[ERROR] !ENTRY org.eclipse.equinox.launcher 4 0 2020-01-07 09:51:55.419
[ERROR] !MESSAGE Exception launching the Eclipse Platform:
[ERROR] !STACK
[ERROR] java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
[ERROR] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
[ERROR] 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:650)
[ERROR] 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
[ERROR] 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
[ERROR] 	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
[ERROR] 	at org.eclipse.core.launcher.Main.main(Main.java:34)
```

I'm not sure why this is the case. It doesn't hit this trouble in the original setup when pointed at an update site generated from the same macOS Notes 11 installation, and it didn't seem to help to ZIP up the expanded bundles.
